name: C/C++ CI

on:
   workflow_dispatch:
jobs:
  ubuntu-build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build project
      uses: nicledomaS/cmake_build_action@v1.4
      with:
        submodule_update: ON
       
