name: make hashbrowns

on:
  push:
    paths:
      - 'dll/latest.dll'  
      - 'dll/beta.dll'    
  workflow_dispatch:

jobs:
  
  build_files:
    runs-on: windows-latest

    steps:
      - name: checkut repo
        uses: actions/checkout@v3

      
      - name: Get CMake
        uses: lukka/get-cmake@latest
      - name: Load cmake cache
        run:
          cmake .
      - name: Build DLL
        run: 
          mkdir build && cmake -S . -B build/ && cmake --build build/ --config Release
          && tree
            
      
