name: make hashbrowns

on:
  push:
    paths:
      - 'dll/latest.dll'  
      - 'dll/beta.dll'    
  workflow_dispatch:

jobs:
  
  build_files:
    runs-on: windows-latest

    steps:
      - name: checkut repo
        uses: actions/checkout@v3

      - name: Build & Test
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          # will set the CC & CXX for cmake
          build-type: Release
      - name: tree
        run:
          tree
      
