name: C/C++ CI

on:
   workflow_dispatch:
jobs:
  ubuntu-build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: CMAKE Cache
      run:
          cmake . 
    - name: Build
      run:
         ./build.bat &&
         cmake --build .
