name: C/C++ CI

on:
  workflow_dispatch:

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v4

    
    - name: Set Up MSVC Environment
      uses: ilammy/msvc-dev-cmd@v1

    
    - name: Configure CMake
      run: |
        cmake -S . -B build -G "Ninja" -DCMAKE_CXX_COMPILER=cl -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_STANDARD=23 -DCMAKE_BUILD_TYPE=Release

    
    - name: Build DLL
      run: |
          cmake --build build
    - name : tree
      run: | 
        tree
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.1
      with:
        name: Flarial DLL
        path: D:\a\dll
        
                
    
