name: make hashbrowns

on:
  push:
    paths:
      - 'dll/latest.dll'  
      - 'dll/beta.dll'    
  workflow_dispatch:

jobs:
  
  build_files:
    runs-on: windows-latest

    steps:
      - name: checkut repo
        uses: actions/checkout@v3

      
      - name: Get CMake
        uses: lukka/get-cmake@latest
      - name: Build DLL
        run:
          
          cmake .
          | cmake --build . --config Release

      - name: Upload DLL
        run: 
          tree
          
            
      
