name: make hashbrowns

on:
  push:
    paths:
      - 'dll/latest.dll'  
      - 'dll/beta.dll'    
  workflow_dispatch:

jobs:
  build_files:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

  # Option 2: specify 'latest' or 'latestrc' in the input version arguments:
      - name: Get latest CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latestrc      # <--= optional, use the latest release candidate (notice the 'rc' suffix).
          ninjaVersion: latest        # <--= optional, use the latest release (non candidate).

      - name: Create Build Directory
        run: mkdir build

      - name: Configure CMake
        working-directory: ./build
        run: cmake .. #-G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_STANDARD_REQUIRED=ON


      - name: Build DLL
        working-directory: ./build
        run: make ..

      - name: List Directory Contents
        run: ls
